server.port=8081
spring.application.name=EmailService
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=donot_reply@paylineindia.com
spring.mail.password=D0n0t$ep!y
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
